name: Auto-sort ATC CSV

permissions:
  contents: write
  pull-requests: read

on:
  push:
    paths: [ "atc_sources.csv" ]
  pull_request:
    paths: [ "atc_sources.csv" ]

jobs:
  sort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Auto-sort (in place)
        shell: pwsh
        run: ./tools/Sort-ATCSources.ps1 -InPlace

      # Push only for same-repo branches (not forks)
      - name: Commit sorted file (same-repo branches only)
        if: |
          github.event_name == 'push' ||
          (github.event_name == 'pull_request' &&
           github.event.pull_request.head.repo.full_name == github.repository)
        run: |
          if git diff --quiet; then
            echo "No sorting changes."
          else
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add atc_sources.csv
            git commit -m "chore: canonical sort atc_sources.csv"
            git push
          fi

      # For fork PRs (no push), just verify
      - name: Verify (fork PRs)
        if: |
          github.event_name == 'pull_request' &&
          github.event.pull_request.head.repo.full_name != github.repository
        shell: pwsh
        run: ./tools/Sort-ATCSources.ps1 -Check

